package app.silofs.server

import io.ktor.http.ContentType
import io.ktor.http.HttpHeaders
import io.ktor.http.HttpStatusCode
import io.ktor.http.withCharset
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.calllogging.CallLogging
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.plugins.cors.routing.CORS
import io.ktor.server.plugins.defaultheaders.DefaultHeaders
import io.ktor.server.plugins.partialcontent.PartialContent
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.request.httpMethod
import io.ktor.server.request.path
import io.ktor.server.response.respondText
import app.silofs.auth.SigV4Auth
import app.silofs.common.RequestIds
import app.silofs.common.S3ErrorCode
import app.silofs.common.S3Exception
import app.silofs.common.s3Tag
import app.silofs.common.s3XmlDocument
import org.slf4j.LoggerFactory
import org.slf4j.event.Level

/**
 * Wires all Ktor plugins. Status pages convert [S3Exception] into the standard
 * S3 XML error body and reuse the per-call request ID generated by
 * [RequestIdPlugin].
 */
fun Application.installPlugins(config: ServerConfig) {
    install(DefaultHeaders)
    install(RequestIdPlugin)
    install(CallLogging) {
        level = Level.INFO
        filter { call -> call.request.path() !in setOf("/healthz", "/readyz", "/metricsz") }
        mdc("s3-request-id") { call -> call.requestId() ?: "-" }
    }
    install(ContentNegotiation) {
        json()
    }
    install(CORS) {
        anyHost()
        allowCredentials = true
        allowNonSimpleContentTypes = true
    }
    install(PartialContent) {
        maxRangeCount = 1
    }

    install(SigV4Auth) {
        credentialProvider = config.credentialProvider
        region = config.region
        publicPaths = setOf("/healthz", "/readyz", "/metricsz")
        enabled = true
        maxClockSkewSeconds = config.sigv4MaxClockSkewSeconds
    }

    install(StatusPages) {
        exception<S3Exception> { call, cause ->
            // Reuse the request ID generated by RequestIdPlugin if available;
            // otherwise generate a fresh one (e.g. for errors thrown from the
            // auth plugin before RequestIdPlugin has run).
            val requestId = call.requestId() ?: RequestIds.newRequestId()
            val extendedId = call.extendedRequestId() ?: requestId
            // Ensure the request-id headers are present on the error response
            // even if the plugin failed to attach them.
            if (call.response.headers[HttpHeaders.Server] == null) {
                call.response.headers.append(HttpHeaders.Server, "AmazonS3")
            }
            if (call.response.headers["x-amz-request-id"] == null) {
                call.response.headers.append("x-amz-request-id", requestId)
            }
            if (call.response.headers["x-amz-id-2"] == null) {
                call.response.headers.append("x-amz-id-2", extendedId)
            }
            // For 304 Not Modified the body must be empty (RFC 7232 §4.1).
            if (cause.errorCode == S3ErrorCode.NotModified) {
                call.response.status(HttpStatusCode.NotModified)
                call.response.headers.append(HttpHeaders.ContentLength, "0")
                return@exception
            }
            val body = s3XmlDocument("Error") {
                s3Tag("Code", cause.errorCode.code)
                s3Tag("Message", cause.message)
                s3Tag("Resource", cause.resource ?: call.request.local.uri)
                s3Tag("RequestId", requestId)
            }
            val status = HttpStatusCode.fromValue(cause.errorCode.httpStatus)
            call.respondText(body, ContentType.Application.Xml.withCharset(Charsets.UTF_8), status)
        }
        exception<Throwable> { call, cause ->
            val log = LoggerFactory.getLogger("StatusPages")
            log.error("Unhandled exception on ${call.request.httpMethod.value} ${call.request.path()}", cause)
            val requestId = call.requestId() ?: RequestIds.newRequestId()
            if (call.response.headers["x-amz-request-id"] == null) {
                call.response.headers.append("x-amz-request-id", requestId)
            }
            val body = s3XmlDocument("Error") {
                s3Tag("Code", S3ErrorCode.InternalError.code)
                s3Tag("Message", "We encountered an internal error. Please try again.")
                s3Tag("Resource", call.request.local.uri)
                s3Tag("RequestId", requestId)
            }
            call.respondText(body, ContentType.Application.Xml.withCharset(Charsets.UTF_8), HttpStatusCode.InternalServerError)
        }
    }
}
